/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.blade.basic.model.impl;

import com.liferay.blade.basic.model.Flight;
import com.liferay.blade.basic.service.FlightLocalServiceUtil;

/**
 * The extended model base implementation for the Flight service. Represents a row in the &quot;Flight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FlightImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FlightImpl
 * @see Flight
 * @generated
 */
public abstract class FlightBaseImpl extends FlightModelImpl implements Flight {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a flight model instance should use the <code>Flight</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			FlightLocalServiceUtil.addFlight(this);
		}
		else {
			FlightLocalServiceUtil.updateFlight(this);
		}
	}

}