/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.notification.admin.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.notification.admin.model.NotificationAdminTemplate;
import com.liferay.notification.admin.service.NotificationAdminTemplateLocalService;
import com.liferay.notification.admin.service.NotificationAdminTemplateLocalServiceUtil;
import com.liferay.notification.admin.service.persistence.NotificationAdminTemplatePersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the notification admin template local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.notification.admin.service.impl.NotificationAdminTemplateLocalServiceImpl}.
 * </p>
 *
 * @author Gabriel Albuquerque
 * @see com.liferay.notification.admin.service.impl.NotificationAdminTemplateLocalServiceImpl
 * @generated
 */
public abstract class NotificationAdminTemplateLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   NotificationAdminTemplateLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NotificationAdminTemplateLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>NotificationAdminTemplateLocalServiceUtil</code>.
	 */

	/**
	 * Adds the notification admin template to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationAdminTemplateLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationAdminTemplate the notification admin template
	 * @return the notification admin template that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NotificationAdminTemplate addNotificationAdminTemplate(
		NotificationAdminTemplate notificationAdminTemplate) {

		notificationAdminTemplate.setNew(true);

		return notificationAdminTemplatePersistence.update(
			notificationAdminTemplate);
	}

	/**
	 * Creates a new notification admin template with the primary key. Does not add the notification admin template to the database.
	 *
	 * @param notificationAdminTemplateId the primary key for the new notification admin template
	 * @return the new notification admin template
	 */
	@Override
	@Transactional(enabled = false)
	public NotificationAdminTemplate createNotificationAdminTemplate(
		long notificationAdminTemplateId) {

		return notificationAdminTemplatePersistence.create(
			notificationAdminTemplateId);
	}

	/**
	 * Deletes the notification admin template with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationAdminTemplateLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationAdminTemplateId the primary key of the notification admin template
	 * @return the notification admin template that was removed
	 * @throws PortalException if a notification admin template with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NotificationAdminTemplate deleteNotificationAdminTemplate(
			long notificationAdminTemplateId)
		throws PortalException {

		return notificationAdminTemplatePersistence.remove(
			notificationAdminTemplateId);
	}

	/**
	 * Deletes the notification admin template from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationAdminTemplateLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationAdminTemplate the notification admin template
	 * @return the notification admin template that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NotificationAdminTemplate deleteNotificationAdminTemplate(
		NotificationAdminTemplate notificationAdminTemplate) {

		return notificationAdminTemplatePersistence.remove(
			notificationAdminTemplate);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return notificationAdminTemplatePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			NotificationAdminTemplate.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return notificationAdminTemplatePersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.admin.model.impl.NotificationAdminTemplateModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return notificationAdminTemplatePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.admin.model.impl.NotificationAdminTemplateModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return notificationAdminTemplatePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return notificationAdminTemplatePersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return notificationAdminTemplatePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public NotificationAdminTemplate fetchNotificationAdminTemplate(
		long notificationAdminTemplateId) {

		return notificationAdminTemplatePersistence.fetchByPrimaryKey(
			notificationAdminTemplateId);
	}

	/**
	 * Returns the notification admin template with the matching UUID and company.
	 *
	 * @param uuid the notification admin template's UUID
	 * @param companyId the primary key of the company
	 * @return the matching notification admin template, or <code>null</code> if a matching notification admin template could not be found
	 */
	@Override
	public NotificationAdminTemplate
		fetchNotificationAdminTemplateByUuidAndCompanyId(
			String uuid, long companyId) {

		return notificationAdminTemplatePersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the notification admin template with the primary key.
	 *
	 * @param notificationAdminTemplateId the primary key of the notification admin template
	 * @return the notification admin template
	 * @throws PortalException if a notification admin template with the primary key could not be found
	 */
	@Override
	public NotificationAdminTemplate getNotificationAdminTemplate(
			long notificationAdminTemplateId)
		throws PortalException {

		return notificationAdminTemplatePersistence.findByPrimaryKey(
			notificationAdminTemplateId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			notificationAdminTemplateLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NotificationAdminTemplate.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationAdminTemplateId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			notificationAdminTemplateLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			NotificationAdminTemplate.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationAdminTemplateId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			notificationAdminTemplateLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NotificationAdminTemplate.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"notificationAdminTemplateId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod
				<NotificationAdminTemplate>() {

				@Override
				public void performAction(
						NotificationAdminTemplate notificationAdminTemplate)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, notificationAdminTemplate);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(
					NotificationAdminTemplate.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return notificationAdminTemplatePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return notificationAdminTemplateLocalService.
			deleteNotificationAdminTemplate(
				(NotificationAdminTemplate)persistedModel);
	}

	@Override
	public BasePersistence<NotificationAdminTemplate> getBasePersistence() {
		return notificationAdminTemplatePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return notificationAdminTemplatePersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns the notification admin template with the matching UUID and company.
	 *
	 * @param uuid the notification admin template's UUID
	 * @param companyId the primary key of the company
	 * @return the matching notification admin template
	 * @throws PortalException if a matching notification admin template could not be found
	 */
	@Override
	public NotificationAdminTemplate
			getNotificationAdminTemplateByUuidAndCompanyId(
				String uuid, long companyId)
		throws PortalException {

		return notificationAdminTemplatePersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the notification admin templates.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.notification.admin.model.impl.NotificationAdminTemplateModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of notification admin templates
	 * @param end the upper bound of the range of notification admin templates (not inclusive)
	 * @return the range of notification admin templates
	 */
	@Override
	public List<NotificationAdminTemplate> getNotificationAdminTemplates(
		int start, int end) {

		return notificationAdminTemplatePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of notification admin templates.
	 *
	 * @return the number of notification admin templates
	 */
	@Override
	public int getNotificationAdminTemplatesCount() {
		return notificationAdminTemplatePersistence.countAll();
	}

	/**
	 * Updates the notification admin template in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect NotificationAdminTemplateLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param notificationAdminTemplate the notification admin template
	 * @return the notification admin template that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NotificationAdminTemplate updateNotificationAdminTemplate(
		NotificationAdminTemplate notificationAdminTemplate) {

		return notificationAdminTemplatePersistence.update(
			notificationAdminTemplate);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			NotificationAdminTemplateLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		notificationAdminTemplateLocalService =
			(NotificationAdminTemplateLocalService)aopProxy;

		_setLocalServiceUtilService(notificationAdminTemplateLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NotificationAdminTemplateLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return NotificationAdminTemplate.class;
	}

	protected String getModelClassName() {
		return NotificationAdminTemplate.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				notificationAdminTemplatePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		NotificationAdminTemplateLocalService
			notificationAdminTemplateLocalService) {

		try {
			Field field =
				NotificationAdminTemplateLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, notificationAdminTemplateLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected NotificationAdminTemplateLocalService
		notificationAdminTemplateLocalService;

	@Reference
	protected NotificationAdminTemplatePersistence
		notificationAdminTemplatePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}