/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.blade.basic.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ExternalReferenceCodeModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Flight service. Represents a row in the &quot;Flight&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.blade.basic.model.impl.FlightModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.blade.basic.model.impl.FlightImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Flight
 * @generated
 */
@ProviderType
public interface FlightModel
	extends BaseModel<Flight>, ExternalReferenceCodeModel, GroupedModel,
			MVCCModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flight model instance should use the {@link Flight} interface instead.
	 */

	/**
	 * Returns the primary key of this flight.
	 *
	 * @return the primary key of this flight
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this flight.
	 *
	 * @param primaryKey the primary key of this flight
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this flight.
	 *
	 * @return the mvcc version of this flight
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this flight.
	 *
	 * @param mvccVersion the mvcc version of this flight
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this flight.
	 *
	 * @return the uuid of this flight
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this flight.
	 *
	 * @param uuid the uuid of this flight
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this flight.
	 *
	 * @return the external reference code of this flight
	 */
	@AutoEscape
	@Override
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this flight.
	 *
	 * @param externalReferenceCode the external reference code of this flight
	 */
	@Override
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the flight ID of this flight.
	 *
	 * @return the flight ID of this flight
	 */
	public long getFlightId();

	/**
	 * Sets the flight ID of this flight.
	 *
	 * @param flightId the flight ID of this flight
	 */
	public void setFlightId(long flightId);

	/**
	 * Returns the group ID of this flight.
	 *
	 * @return the group ID of this flight
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this flight.
	 *
	 * @param groupId the group ID of this flight
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this flight.
	 *
	 * @return the company ID of this flight
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this flight.
	 *
	 * @param companyId the company ID of this flight
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this flight.
	 *
	 * @return the user ID of this flight
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this flight.
	 *
	 * @param userId the user ID of this flight
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this flight.
	 *
	 * @return the user uuid of this flight
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this flight.
	 *
	 * @param userUuid the user uuid of this flight
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this flight.
	 *
	 * @return the user name of this flight
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this flight.
	 *
	 * @param userName the user name of this flight
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this flight.
	 *
	 * @return the create date of this flight
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this flight.
	 *
	 * @param createDate the create date of this flight
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this flight.
	 *
	 * @return the modified date of this flight
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this flight.
	 *
	 * @param modifiedDate the modified date of this flight
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the flight number of this flight.
	 *
	 * @return the flight number of this flight
	 */
	@AutoEscape
	public String getFlightNumber();

	/**
	 * Sets the flight number of this flight.
	 *
	 * @param flightNumber the flight number of this flight
	 */
	public void setFlightNumber(String flightNumber);

	/**
	 * Returns the active of this flight.
	 *
	 * @return the active of this flight
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this flight is active.
	 *
	 * @return <code>true</code> if this flight is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this flight is active.
	 *
	 * @param active the active of this flight
	 */
	public void setActive(boolean active);

	/**
	 * Returns the capacity of this flight.
	 *
	 * @return the capacity of this flight
	 */
	public int getCapacity();

	/**
	 * Sets the capacity of this flight.
	 *
	 * @param capacity the capacity of this flight
	 */
	public void setCapacity(int capacity);

	/**
	 * Returns the flight date of this flight.
	 *
	 * @return the flight date of this flight
	 */
	public Date getFlightDate();

	/**
	 * Sets the flight date of this flight.
	 *
	 * @param flightDate the flight date of this flight
	 */
	public void setFlightDate(Date flightDate);

	@Override
	public Flight cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}