import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('button', { name: 'Sign In' }).click();
await page.getByText('Email Address Password Caps Lock is on. Remember Me').click();
await page.getByLabel('Email Address').click();
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').press('ArrowLeft');
await page.getByLabel('Email Address').fill('est@liferay.com');
await page.getByLabel('Email Address').press('ArrowRight');
await page.getByLabel('Email Address').fill('test@liferay.com');
await page.getByLabel('Password').click();
await page.getByLabel('Password').fill('test');
await page.getByLabel('Sign In- Loading').getByRole('button', { name: 'Sign In' }).click();
await page.locator('#main-content div').filter({ hasText: 'Welcome to Liferay Enjoy using the best DXP on Earth!' }).nth(3).click();
await page.getByLabel('Open Applications MenuCtrl+Alt+A').click();
await page.getByRole('tab', { name: 'Control Panel' }).click();
await page.getByRole('menuitem', { name: 'Objects' }).click();
await page.getByRole('link', { name: 'Commerce Order', exact: true }).click();
await page.getByRole('link', { name: 'Actions' }).click();
await page.getByTestId('fdsCreationActionButton').click();
await page.frameLocator('iframe').getByPlaceholder('Text to translate...').click();
await page.frameLocator('iframe').getByPlaceholder('Text to translate...').fill('aaaaaa');
await page.frameLocator('iframe').getByRole('tab', { name: 'Action Builder' }).click();
await page.frameLocator('iframe').getByText('Choose a Trigger').click();
await page.frameLocator('iframe').getByRole('option', { name: 'On Order Status Update' }).click();
await page.frameLocator('iframe').getByText('Choose an Action').click();
await page.frameLocator('iframe').getByRole('option', { name: 'Notification' }).click();
});